name: default
on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - main
      - develop
jobs:
  build:
    strategy:
      matrix:
        os: [ macos-latest, ubuntu-latest, windows-latest ]
        java: [ 17 ]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: ${{ matrix.java }}
      - run: ./gradlew clean build --stacktrace
